# Generated by Django 3.1.2 on 2020-11-13 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='attributes',
            name='validator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.validators'),
        ),
    ]
